# указываю, к каким серверам будет обращаться Ansible
[web_servers]
# указываю Ansible подключаться к самому себе локально (т.к. покачто у меня нет внешнего сервера)
localhost ansible_connection=local
