# describe the tasks that Ansible must perform

- name: First server setup
  hosts: web_servers
  vars:
    # declare a variable for our template
    nextcloud_max_upload: "1G"

  tasks:
    - name: enter a welcome message
      debug:
        msg: "start generating the config from the template..."

    - name: Generate Nextcloud config from template
      template:
        src: "templates/nextcloud_nginx.conf.j2"
        dest: "~/IaC/nextcloud_nginx.conf"

